config/routes.rb
Senate2::Application.routes.draw do
  get "admin/index"

  post "tag/tag", :as => :tag

  get "tag/untag/:tag", :controller => 'tag', :action => 'untag', :as => :untag

  get "tagged/:tag", :controller => 'tag', :action => 'tagged', :as => :tagged

  resources :assemblies

	get "comments/create"

	get "home/index"

	resources :news_items
	

	resources :chambers do
		resources :comments do
			resources :comments
		end
		resources :events do
			member do
				get 'attend'
				get 'unattend'
			end
		end
		resources :titles do
			member do
				post 'change'
			end
		end
		resources :proposals do 
			resources :permissions
			resources :comments
			member do
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :boards do
			resources :permissions
			resources :comments
			member do 
				post 'comment'
				get 'discuss'
			end
		end
		resources :ballots do
			resources :permissions
			member do 
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :permissions
		resources :announcements do
			resources :comments
			member do
				get 'discuss'
			end
		end
		member do
			post 'announce'
		end
	end
	resources :groups do
		member do
			post :change
		end
	end

	match 'sessions/new' => 'sessions#new'
	resources :users
	resources :sessions do
		get :delete, :on => :collection, :action => :destroy
	end

	root :to => 'home#index'

end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
	acts_as_taggable
	belongs_to :chamber
	belongs_to :user
	has_many :ballot_remarks, :dependent => :destroy
	has_many :permissions, :as => :securable, :dependent => :destroy
	attr_accessor :options_raw
	before_create :set_options
	serialize :options, Hash

	def display
		self.title
	end

	def set_options
		x = {}
		i = 0
		self.options_raw.split("\n").each do |l|
			i += 1
			x[i] = l.strip	
		end
		self.options = x	
	end

	def secures user
		x = nil
		self.permissions.sort{|a,b| b.priority <=> a.priority}.each do |p|
			if (p.authorizes? user)
				x = p
			else
			end
		end
		if x
			return x
		else
			y = self.chamber.secures user
			if y
				return y
			else
				return nil
			end
		end
	end

	def secures_without user, skip
		self.permissions.sort{|a,b| a.priority <=> b.priority}.each do |p|
			return p if p.authorizes? user && p != skip
		end
		self.chamber.secures? user
	end

	def users
		(self.principals + self.chamber.principals).map {|x| x.users}.flatten.uniq
	end

	def can? user, right
		p = secures(user)
		r = nil
		if p
			case right
			when :read
				r=p.read
			when :write
				r=p.write
			when :execute, :admin
				r=p.execute
			end
		else
			r=false
			return '*' if user.admin?
		end
		r
	end

	def permissions
		Permission.where(:securable_type => "Ballot").where(:securable_id => self.id)
	end

	def superparent
		self
	end

	def voted? user
		if self.ballot_remarks.where(:user_id => user.id)
			self.ballot_remarks.where(:user_id => user.id).first
		else
			false
		end
	end
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
	before_filter :find_chamber
	before_filter :check_for_user
	# GET /ballots
	# GET /ballots.json
	def index
		@ballots = @chamber.ballots.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @ballots }
		end
	end

	# GET /ballots/1
	# GET /ballots/1.json
	def show
		@ballot = Ballot.find(params[:id])
		unless @ballot.can?(current_user, :read) || current_user.admin?
			redirect_to @ballot.chamber, :error => "Access Denied" 
		else
			respond_to do |format|
				format.html # show.html.erb
				format.json { render json: @ballot }
			end
		end
	end

	def inspect
		@ballot = Ballot.find(params[:id])
	end

	# GET /ballots/new
	# GET /ballots/new.json
	def new
		@ballot = Ballot.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @ballot }
		end
	end

	# POST /ballots
	# POST /ballots.json
	def create
		@ballot = Ballot.new(params[:ballot])
		@ballot.set_options

		unless @ballot.chamber.can?(current_user, :read)
			redirect_to @ballot.chamber, :error => "Access Denied" 
		end

		respond_to do |format|
			if @ballot.save
				Log.create(:user => current_user, :chamber => @chamber, :action_type => "Ballot", :action_id => @ballot.id, :comment => "created a new ballot")
				format.html { redirect_to [@chamber,@ballot], notice: 'Ballot was successfully created.' }
				format.json { render json: @ballot, status: :created, location: @ballot }
			else
				format.html { render action: "new" }
				format.json { render json: @ballot.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /ballots/1
	# DELETE /ballots/1.json
	def destroy
		@ballot = Ballot.find(params[:id])
		if @ballot
			@ballot.destroy
				Log.where(:action_type => 'Ballot', :action_id => params[:id]).each do |l|
					l.destroy
				end
				Log.create(:user => current_user, :chamber => @chamber, :action_type => nil, :action_id => nil, :comment => "removed a ballot")
			respond_to do |format|
				format.html { redirect_to chamber_ballots_url(@chamber) }
				format.json { head :no_content }
			end
		else
			redirect_to session[:return_to], :notice => "Ballot was already deleted."
		end
	end

	def vote
		@ballot = Ballot.find(params[:id])
		if BallotRemark.where(:ballot_id => @ballot.id, :user_id => current_user.id).count > 0
			redirect_to chamber_ballots_path(@chamber), :info => 'You already voted.'
		else
			BallotRemark.create!(:ballot_id => @ballot.id, :user_id => current_user.id, :remark => params[:remark])
			Log.create(:user => current_user, :chamber => @chamber, :action_type => "Ballot", :action_id => @ballot.id, :comment => "voted on a ballot")
			redirect_to chamber_ballots_path(@chamber), :info => 'Your vote has been submitted.'
		end
	end

	def close
		@ballot = Ballot.find(params[:id])
		@ballot.closed = true
		@ballot.save
		redirect_to [@chamber, @ballot], :info => 'Closed ballot.'
		Log.create(:user => current_user, :chamber => @chamber, :action_type => "Ballot", :action_id => @ballot.id, :comment => "closed a ballot")
	end

	def cancel
		@ballot = Ballot.find(params[:id])
		@ballot.voted?(current_user).delete
		redirect_to chamber_ballots_path(@chamber), :info => 'Your vote has been cancelled.'
	end
end

app/helpers/ballots_helper.rb
module BallotsHelper
end

app/views/ballots/_ballot.html.erb
<% 
	totals = {}
	item.ballot_remarks.each do |remark|
		totals[remark.remark] ? totals[remark.remark] += 1 : totals[remark.remark] = 1
	end
	totals = totals.sort{|a,b| b[1] <=> a[1]}
	named_totals = {}
	totals.each do |i|
		named_totals[item.options[i[0]]] = i[1]
	end

%>

<div class="proposal<%= ' old' if item.closed %>">
	<%= link_to [@chamber, item] do %><h3>Ballot #<%= item.id %> - <%= item.title %></h3><% end %>
	<h4>Proposed by <%= link_to (@chamber ? item.user.titleize(@chamber): item.user.name), item.user %> <%= time_delta item.created_at %></h4>
	<% if can :execute, item %>
		<h4><%= link_to (named_totals.length > 0 ? named_totals.map{|e| "#{e[0]}: #{e[1]}"}.join(', ') + " - See Details" : "No Votes Yet").html_safe, inspect_chamber_ballot_path(@chamber, item) %></h4>
	<% end %>
	<%= markdown item.content %>


	<% if item.closed %>
		<p>This ballot is closed.</p>
	<% else %>

		<% if item.voted? current_user %>
			<p>You voted already! <%= link_to "Cancel your vote", cancel_chamber_ballot_path(@chamber, item), :class => 'btn btn-mini btn-warning'  %></p>
		<% else %> 
			<% if can(:write, item) %>
				<%= form_tag vote_chamber_ballot_path(@chamber, item), :class => "form-horizontal" %> 
				<%= hidden_field_tag :ballot_id, item.id %> 
				<%= hidden_field_tag :user_id, current_user.id %>

				<table>
					<tr>
						<th colspan="2">
							What do you think: 	
						</th>
					</tr>					
					<% item.options.each do |o| %>
						<tr>
							<td><%= label_tag :remark, (o[1].to_s) %></td>
							<td><%= radio_button_tag :remark, o[0] %></td>
						</tr>
					<% end %>
				</table>
				<%= submit_tag "Vote!", :class => "btn btn-success" %>
			<% end %>
		<% end %>
	<% end %>
	<% if can(:execute, item) %>
		<div class="announce_foot">

			<%= link_to "Close", close_chamber_ballot_path(@chamber, item), :class => 'btn btn-warning btn-mini' if !item.closed%>  
			<%= link_to "Delete", [@chamber, item], :method => :delete, :class => 'btn btn-danger btn-mini' %> 
			<%= link_to "Permissions", chamber_ballot_permissions_path(@chamber, item), :class => 'btn btn-mini btn-info' if !item.closed%>

		</div>
	<% end %>

	<% if @tags %>
		<p>
		Tagged with: <%= item.tag_list %>
		</p>
	<% end %>
</div>


app/views/ballots/_form.html.erb
<%= form_for [@chamber, @ballot] do |f| %>
	<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
	</p>
	<p>
	<%= f.label :anonymous %>
	<%= f.check_box :anonymous %>
	<i>People can't see how other people voted on an anonymous ballot</i>
	</p>
	<table>
		<tr>
			<td>
				<%= f.label :content %><br />
				<%= f.text_area :content %>
				</td><td>
				Options - 1 per line<br/>
				<%= f.text_area :options_raw %>
	</td></tr></table>
	<p>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :closed, :value => false %>
	<%= f.hidden_field :chamber_id, :value => @chamber.id %>
	</p>
	<p><%= f.submit "Create Ballot", :class => 'btn btn-primary, btn-large' %></p>
<% end %>

app/views/ballots/edit.html.erb
<%- model_class = @ballot.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/ballots/index.html.erb
<h1>Ballots in <%= @chamber.title %></h1>

<% @ballots.each do |proposal| %>
	<%= render :partial => 'ballot', :locals => {:item => proposal} %>
<% end %>


<% if can(:admin) %><%= link_to "Submit New Ballot", new_chamber_ballot_path(@chamber), :class => 'btn btn-primary' %> <% end %>

app/views/ballots/inspect.html.erb
<% 
	require 'google_chart'
	totals = {}
	@ballot.ballot_remarks.each do |remark|
		totals[remark.remark] ? totals[remark.remark] += 1 : totals[remark.remark] = 1
	end
	totals = totals.sort{|a,b| b[1] <=> a[1]}
	named_totals = {}
	totals.each do |i|
		named_totals[@ballot.options[i[0]]] = i[1]
	end

	GoogleChart::PieChart.new('800x320', "Ballot Votes", false) do |c|
		@ballot.options.each_pair do |i, v|
			if named_totals.has_key?(v)
				c.data "#{v} - #{named_totals[v]}", named_totals[v]
			else
				c.data "#{v} - 0", 0
			end
		end
		@chart = c.to_url
	end
%>

<div style="display: block; margin-left: auto;"><%= image_tag @chart, :size => '800x320' %></div>

<% unless @ballot.anonymous %>
<% @ballot.options.each_pair do |i, k| %>
	<h3><%= k %> - <%= named_totals[k] || 0 %></h3>
	<table class="table table-condensed table-bordered table-striped" %>
		<% @ballot.ballot_remarks.where(:remark => i).in_groups_of(6) do |group| %>
		<tr>
			<% group.each do |r| %>
				<td><%= link_to r.user.name, r.user if r %></td>
			<% end %>
		</tr>
	<% end %>
</table>
<% end %>
<% end %>

app/views/ballots/new.html.erb
<%- model_class = @ballot.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/ballots/show.html.erb
<%= render :partial => 'ballot', :locals => {:item => @ballot} %>

<%= tagbox @ballot %>