config/routes.rb
Senate2::Application.routes.draw do
  get "admin/index"

  post "tag/tag", :as => :tag

  get "tag/untag/:tag", :controller => 'tag', :action => 'untag', :as => :untag

  get "tagged/:tag", :controller => 'tag', :action => 'tagged', :as => :tagged

  resources :assemblies

	get "comments/create"

	get "home/index"

	resources :news_items
	

	resources :chambers do
		resources :comments do
			resources :comments
		end
		resources :events do
			member do
				get 'attend'
				get 'unattend'
			end
		end
		resources :titles do
			member do
				post 'change'
			end
		end
		resources :proposals do 
			resources :permissions
			resources :comments
			member do
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :boards do
			resources :permissions
			resources :comments
			member do 
				post 'comment'
				get 'discuss'
			end
		end
		resources :ballots do
			resources :permissions
			member do 
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :permissions
		resources :announcements do
			resources :comments
			member do
				get 'discuss'
			end
		end
		member do
			post 'announce'
		end
	end
	resources :groups do
		member do
			post :change
		end
	end

	match 'sessions/new' => 'sessions#new'
	resources :users
	resources :sessions do
		get :delete, :on => :collection, :action => :destroy
	end

	root :to => 'home#index'

end

app/views/admin/index.html.erb
<h1>Administrator Control Panel</h1>
<h2>Users & Groups</h2>
<table class="table">
	<tr>
		<td><%= link_to "Manage Users", users_path, :class => "btn btn-large btn-block" %> </td>
		<td><%= link_to "Manage Groups", groups_path, :class => "btn btn-large btn-block" %> </td>
		<td><%= link_to "New Group", new_group_path, :class => "btn btn-large btn-block" %> </td>
	</td>
</table>

<h2>Chambers & Assemblies</h2>
<table class="table">
	<tr>
		<td><%= link_to "All Chambers", chambers_path, :class => "btn btn-large btn-block" %> </td>
		<td><%= link_to "New Chamber", new_chamber_path, :class => "btn btn-large btn-block" %> </td>
		<td><%= link_to "All Assemblies", assemblies_path, :class => "btn btn-large btn-block" %> </td>
		<td><%= link_to "New Assembly", new_assembly_path, :class => "btn btn-large btn-block" %> </td>
	</td>
</table>