config/routes.rb
Senate2::Application.routes.draw do
  get "admin/index"

  post "tag/tag", :as => :tag

  get "tag/untag/:tag", :controller => 'tag', :action => 'untag', :as => :untag

  get "tagged/:tag", :controller => 'tag', :action => 'tagged', :as => :tagged

  resources :assemblies

	get "comments/create"

	get "home/index"

	resources :news_items
	

	resources :chambers do
		resources :comments do
			resources :comments
		end
		resources :events do
			member do
				get 'attend'
				get 'unattend'
			end
		end
		resources :titles do
			member do
				post 'change'
			end
		end
		resources :proposals do 
			resources :permissions
			resources :comments
			member do
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :boards do
			resources :permissions
			resources :comments
			member do 
				post 'comment'
				get 'discuss'
			end
		end
		resources :ballots do
			resources :permissions
			member do 
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :permissions
		resources :announcements do
			resources :comments
			member do
				get 'discuss'
			end
		end
		member do
			post 'announce'
		end
	end
	resources :groups do
		member do
			post :change
		end
	end

	match 'sessions/new' => 'sessions#new'
	resources :users
	resources :sessions do
		get :delete, :on => :collection, :action => :destroy
	end

	root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@news = NewsItem.all 
		current_user.chambers.each{|c| @news += c.announcements} if current_user
		@news.sort!{|a,b| b.created_at <=> a.created_at}
		@news = @news.first(5)
		render :layout => 'columns'
	end
end

app/views/home/_footbar.html.erb
<% if current_user %>
	<%
		online_users = User.all.delete_if{|u| !u.online?}
	%>
	<div class="navbar navbar-fixed-bottom hidden-phone">
		<div class="navbar-inner" style="padding-top: -10px; padding-bottom: -10px; min-height: none;">
			<div class="container">
				<ul class="nav" style="margin: auto;">
					<li class="dropup">
					<a href="#"><%= i('user')%> Online Users <span class="badge"><%= online_users.count %></span> <%= i 'chevron-up' %></a>
					<ul class="dropdown-menu">
						<% online_users.each do |u| %>
							<li><%= link_to u.name, u %></li>						
						<% end %>
					</ul>
					</li>
					<% if current_user.admin? %>
						<li class="dropup"><a href="<%= admin_index_path %>"  style="color: #111; font-weight: bold;"><%= i 'chevron-up' %> Admin Tools</a>
						<ul class="dropdown-menu">
						<li><%= link_to i('user') + "Users", users_path %></li>
						<li><%= link_to i('list-alt') + "Groups", groups_path %></li>
						<li><%= link_to i('briefcase') + "Chambers", chambers_path %></li>
						<li><%= link_to i('briefcase') + "Assemblies", assemblies_path %></li>
					</ul>
						</li>
					<% end %>

				</ul>
			</div>
		</div>
	</div>
<% end %>

app/views/home/_navbar.html.erb
<div class="navbar navbar-fixed-top hidden-phone">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Senate", root_path, :class => 'brand' %>
			<div class="container nav-collapse">
				<ul class="nav">
					<% if current_user %>
						<li><%= link_to i('user') + " Log Out", delete_sessions_path %></li>
						<li><%= link_to i('edit') + " " + current_user.name, current_user %></li>
						<% if @chamber && @chamber.title != nil %>
							<li class="dropdown"><%= link_to i('briefcase') + ' ' + @chamber.title + " " + i('chevron-down'), @chamber %>
							
							<ul class="dropdown-menu">
							<li><%= link_to i('comment') + ' Discussion', chamber_boards_path(@chamber) %></li>
							<li><%= link_to i('inbox') + ' Proposals', chamber_proposals_path(@chamber) %></li>
							<li><%= link_to i('file') + ' Ballots', chamber_ballots_path(@chamber) %></li>
							<li><%= link_to i('globe') + ' Events', chamber_events_path(@chamber) %></li>
							<% if can(:execute, @chamber) %>
								<li><%= link_to i('lock') + " Permissions", chamber_permissions_path(@chamber) %></li>
								<li><%= link_to i('bullhorn') + " Titles", chamber_titles_path(@chamber) %></li>
							<% end %>
						</ul>
							</li>
						<% else %>
							<li><%= link_to i('briefcase') + "All Chambers", chambers_path %></li>
						<% end %>
					<% else %>
						<li><%= link_to "Log In", root_path %></li>
					<% end %>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% content_for :left do %>
<h2>News</h2>
			<% if @news.length > 0 %>
				<% @news.each do |news| %>
					<%= render :partial => 'news_items/news', :locals => {:item => news} %>
				<% end %>
			<% else %>
				<p>No news items!</p>
			<% end %>

			<p><%= link_to("Submit New News", new_news_item_path, :class => 'btn btn-primary') if current_user && current_user.admin? %></p>
		<% end %>
		<% if current_user %>
				<h2>Your Chambers</h2>

				<% current_user.chambers.each do |chamber| %>
					<%= render :partial => 'chambers/short_chamber', :locals => {:item => chamber} %>
				<% end %>
			<% else %>
				<h1>Log in</h1>  

				<%= form_tag sessions_path, :method => :post do %> 
					<%= hidden_field_tag :return, params[:return] %>
					<p>  
					<%= label_tag :username %><br />  
					<%= text_field_tag :username, params[:username] %>  
					</p>  
					<p>  
					<%= label_tag :password %><br />  
					<%= password_field_tag :password %>  
					</p>  
					<p class="button"><%= submit_tag "Log In", :class => 'btn btn-primary btn-large'%></p>  
				<% end %>  

			<% end %>