config/routes.rb
Senate2::Application.routes.draw do
  get "admin/index"

  post "tag/tag", :as => :tag

  get "tag/untag/:tag", :controller => 'tag', :action => 'untag', :as => :untag

  get "tagged/:tag", :controller => 'tag', :action => 'tagged', :as => :tagged

  resources :assemblies

	get "comments/create"

	get "home/index"

	resources :news_items
	

	resources :chambers do
		resources :comments do
			resources :comments
		end
		resources :events do
			member do
				get 'attend'
				get 'unattend'
			end
		end
		resources :titles do
			member do
				post 'change'
			end
		end
		resources :proposals do 
			resources :permissions
			resources :comments
			member do
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :boards do
			resources :permissions
			resources :comments
			member do 
				post 'comment'
				get 'discuss'
			end
		end
		resources :ballots do
			resources :permissions
			member do 
				get 'close'
				post 'vote'
				get 'cancel'
				get 'inspect'
			end
		end
		resources :permissions
		resources :announcements do
			resources :comments
			member do
				get 'discuss'
			end
		end
		member do
			post 'announce'
		end
	end
	resources :groups do
		member do
			post :change
		end
	end

	match 'sessions/new' => 'sessions#new'
	resources :users
	resources :sessions do
		get :delete, :on => :collection, :action => :destroy
	end

	root :to => 'home#index'

end

app/models/proposal.rb
require 'commentable.rb'

class Proposal < ActiveRecord::Base
	acts_as_taggable
	include CommentableModel
	belongs_to :chamber
	belongs_to :user
	has_many :proposal_remarks, :dependent => :destroy
	has_many :comments, :as => :commentable, :dependent => :destroy

	def display
		self.title
	end

	def secures user
		x = nil
		self.permissions.sort{|a,b| b.priority <=> a.priority}.each do |p|
			if (p.authorizes? user)
				x = p
			else
			end
		end
		if x
			return x
		else
			y = self.chamber.secures user
			if y
				return y
			else
				return nil
			end
		end
	end

	def secures_without user, skip
		self.permissions.sort{|a,b| a.priority <=> b.priority}.each do |p|
			return p if p.authorizes? user && p != skip
		end
		self.chamber.secures? user
	end

	def users
		(self.principals + self.chamber.principals).map {|x| x.users}.flatten.uniq
	end

	def can? user, right
		p = secures(user)
		r = nil
		if p
			case right
			when :read
				r=p.read
			when :write
				r=p.write
			when :execute, :can
				r=p.execute
			end
		else
			r=false
		end
		puts "Proposal##{self.id}: can #{user.name} #{right.to_s}: #{r}"
		r
	end

	def permissions
		Permission.where(:securable_type => "Proposal").where(:securable_id => self.id)
	end

	def score
		sum = 0
		ProposalRemark.where(:proposal_id => self.id).all.each{|x| sum += x.remark}
		sum
	end

	def positive
		ProposalRemark.where(:proposal_id => self.id, :remark => 1).count
	end

	def negative
		ProposalRemark.where(:proposal_id => self.id, :remark => -1).count
	end

	def super_positive
		ProposalRemark.where(:proposal_id => self.id, :remark => 2).count
	end

	def super_negative
		ProposalRemark.where(:proposal_id => self.id, :remark => -2).count
	end

	def neutral
		ProposalRemark.where(:proposal_id => self.id, :remark => 0).count
	end

	def upvotes
		positive + super_positive
	end

	def downvotes
		negative + super_negative
	end
	
	def voted? user
		if self.proposal_remarks.where(:user_id => user.id)
			self.proposal_remarks.where(:user_id => user.id).first
		else
			false
		end
	end

	def superparent
		self
	end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	before_filter :check_for_user
	before_filter :find_chamber
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = @chamber.proposals.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  def inspect
	@proposal = Proposal.find(params[:id])
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])

    respond_to do |format|
      if @proposal.save
				Log.create(:user => current_user, :chamber => @chamber, :action_type => "Proposal", :action_id => @proposal.id, :comment => "created a new proposal")
        format.html { redirect_to [@chamber, @proposal], notice: 'Proposal was successfully created.' }
        format.json { render json: @proposal, status: :created, location: @proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
		if @proposal
		@chamber = @proposal.chamber
    @proposal.destroy
		Log.where(:action_type => "Proposal", :action_id => params[:id]).each do |l|
			l.destroy
		end

    respond_to do |format|
      format.html { redirect_to chamber_proposals_url(@chamber) }
      format.json { head :no_content }
    end
		else
			redirect_to session[:return_to], :notice => "Comment was already deleted."
		end
  end

  def vote
	@proposal = Proposal.find(params[:id])
	if ProposalRemark.where(:proposal_id => @proposal, :user_id => current_user.id).count > 0
		redirect_to [@chamber, @proposal], :info => 'You already voted.'
	else
		ProposalRemark.create!(:proposal_id => @proposal.id, :user_id => current_user.id, :remark => params[:remark])
		Log.create(:user => current_user, :chamber => @chamber, :action_type => "Proposal", :action_id => @proposal.id, :comment => "voted on a proposal")
		redirect_to [@chamber, @proposal], :info => 'Your vote has been submitted.'
	end
	end

  def close
	@proposal = Proposal.find(params[:id])
	@proposal.closed = true
	@proposal.save
		Log.create(:user => current_user, :chamber => @chamber, :action_type => "Proposal", :action_id => @proposal.id, :comment => "closed a proposal")
	redirect_to [@chamber, @proposal], :info => 'Closed proposal.'
  end

  def cancel
	@proposal = Proposal.find(params[:id])
	@proposal.voted?(current_user).delete
	redirect_to [@chamber, @proposal], :info => 'Your vote has been cancelled.'
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= form_for [@chamber, @proposal] do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title, :placeholder => 'Briefly describe your proposal' %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content, :placeholder => 'Describe your proposal in detail' %>
  </p>
  
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :closed, :value => false %>
	<%= f.hidden_field :chamber_id, :value => params[:chamber_id] %>
	<p><%= f.submit :class => 'btn btn-primary' %></p>
<% end %>

app/views/proposals/_proposal.html.erb
<div class="proposal<%= ' old' if item.closed %>">
	<%= link_to [@chamber, item] do %><h3>Proposal #<%= item.id %> - <%= item.title %><% end %> - <%= item.score || 0 %> points</h3>
	<h4>Proposed by <%= link_to (@chamber ? item.user.titleize(@chamber): item.user.name), item.user %> <%= time_delta item.created_at %></h4>
	<h4><%= link_to "See Voting Details", inspect_chamber_proposal_path(@chamber, item) %></h4>
	<%= markdown item.content %>

	<% if item.closed %>
		<p>This proposal is closed.</p>
	<% else %>

		<% if item.voted? current_user %>
			<p>You voted already! <%= link_to "Cancel your vote", cancel_chamber_proposal_path(@chamber, item), :class => 'btn btn-mini btn-warning'  %></p>
		<% else %> 	
			<%= form_tag vote_chamber_proposal_path(@chamber, item) do |f| %> 
				<%= hidden_field_tag :proposal_id, item.id %> 
				<%= hidden_field_tag :user_id, current_user.id %>
				<% if can(:write, item) %>
					What do you think: 	
					<table width="20%">
						<tr>
							<td><a href="#" rel="tooltip" title="Really don't like" onClick="$('#remark_-2').click();"><%= i "thumbs-down" %><%= i "thumbs-down" %></a></td>
							<td><a href="#" rel="tooltip" title="Don't like" onClick="$('#remark_-1').click();"><%= i "thumbs-down" %></a></td>
							<td><a href="#" rel="tooltip" title="Neutral" onClick="$('#remark_0').click();"><%= i "asterisk" %></a></td>
							<td><a href="#" rel="tooltip" title="Like" onClick="$('#remark_1').click();"><%= i "thumbs-up" %></a></td>
							<td><a href="#" rel="tooltip" title="Really like" onClick="$('#remark_2').click();"><%= i "thumbs-up" %><%= i "thumbs-up" %></a></td>
						</tr>
						<tr>
							<td><%= radio_button_tag :remark, -2 %></td>
							<td><%= radio_button_tag :remark, -1 %></td>
							<td><%= radio_button_tag :remark, 0 %></td>
							<td><%= radio_button_tag :remark, 1 %></td>
							<td><%= radio_button_tag :remark, 2 %></td>
						</tr>
						</table>

							<%= submit_tag "Submit", :class => 'btn btn-success btn-mini' %>

						<% end %>
					<% end %>
				<% end %>
			<% end %>
			<div class="announce_foot">
					<% if can(:read, item) %>
						<%= link_to(pluralize(item.count_children, "Comment"), [@chamber, item], :class => 'btn btn-info btn-mini') if item.comments.count > 0%>
						<%= link_to "Reply", [@chamber, item], :class => 'btn btn-mini btn-inverse' if can(:write, item) && !item.closed %>
					<% end %>



					<% if can(:execute, item) %> 
						<%= link_to "Close", close_chamber_proposal_path(@chamber, item), :class => 'btn btn-warning btn-mini' if !item.closed %>  
						<%= link_to "Delete", [@chamber, item], :method => :delete, :class => 'btn btn-danger btn-mini' %> 
						<%= link_to "Permissions", chamber_proposal_permissions_path(@chamber, item), :class => 'btn btn-mini btn-info' if !item.closed%>
					<% end %>
				</div>

<% if @tags %>
	<p>
	Tagged with: <%= item.tag_list %>
	</p>
<% end %>
		</div>

app/views/proposals/_proposal_list.html.erb
<% @proposals.each do |proposal| %>
	<%= render :partial => 'proposal', :locals => {:item => proposal, :depth => nil, :comments => false} %>
<% end %>

app/views/proposals/_proposals.html.erb
<% @proposals.each do |proposal| %>
	<%= render :partial => 'proposal', :locals => {:item => proposal, :depth => nil, :comments => false} %>
<% end %>

app/views/proposals/edit.html.erb
<%- model_class = @proposal.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/proposals/index.html.erb
<h1>Proposals in <%= @chamber.title %></h1>

<% @proposals.sort{|x, y| [(x.closed ? 1 : 0), y.score] <=> [(y.closed ? 1 : 0), x.score]}.each do |proposal| %>
	<%= render :partial => 'proposal', :locals => {:item => proposal} %>
<% end %>


<% if can(:write) %><%= link_to "Submit New Proposal", new_chamber_proposal_path(@chamber), :class => 'btn btn-primary' %> <% end %>

app/views/proposals/inspect.html.erb
<% 
	require 'google_chart'

	GoogleChart::PieChart.new('800x320', "Ballot Votes", false) do |c|
		c.data "Really Like - #{@proposal.super_positive}", @proposal.super_positive
		c.data "Like - #{@proposal.positive}", @proposal.positive
		c.data "Neutral - #{@proposal.neutral}", @proposal.neutral
		c.data "Dislike - #{@proposal.negative}", @proposal.negative
		c.data "Really Dislike - #{@proposal.super_negative}", @proposal.super_negative
		@chart = c.to_url
	end
%>

<div style="display: block; margin-left: auto;"><%= image_tag @chart, :size => '800x320' %></div>

<h3>Really Like - <%= @proposal.super_positive %></h3>
<table class="table table-condensed table-bordered table-striped" %>
	<% @proposal.proposal_remarks.where(:remark => 2).in_groups_of(6) do |group| %>
		<tr>
			<% group.each do |r| %>
				<td><%= link_to r.user.name, r.user if r %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<h3>Like - <%= @proposal.positive %></h3>
<table class="table table-condensed table-bordered table-striped" %>
	<% @proposal.proposal_remarks.where(:remark => 1).in_groups_of(6) do |group| %>
		<tr>
			<% group.each do |r| %>
				<td><%= link_to r.user.name, r.user if r %></td>
			<% end %>
		</tr>
	<% end %>
	</table>
<h3>Neutral - <%= @proposal.neutral %></h3>
<table class="table table-condensed table-bordered table-striped" %>
	<% @proposal.proposal_remarks.where(:remark => 0).in_groups_of(6) do |group| %>
		<tr>
			<% group.each do |r| %>
				<td><%= link_to r.user.name, r.user if r %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<h3>Don't Like - <%= @proposal.negative %></h3>
<table class="table table-condensed table-bordered table-striped" %>
	<% @proposal.proposal_remarks.where(:remark => -1).in_groups_of(6) do |group| %>
		<tr>
			<% group.each do |r| %>
				<td><%= link_to r.user.name, r.user if r %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<h3>Really Don't Like - <%= @proposal.super_negative %></h3>
<table class="table table-condensed table-bordered table-striped" %>
	<% @proposal.proposal_remarks.where(:remark => -2).in_groups_of(6) do |group| %>
		<tr>
			<% group.each do |r| %>
				<td><%= link_to r.user.name, r.user if r %></td>
			<% end %>
		</tr>
	<% end %>
</table>


app/views/proposals/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", chamber_proposals_path(@chamber) %></p>

app/views/proposals/show.html.erb
<%= render :partial => 'proposal', :locals => {:item => @proposal, :depth => nil, :comments => true} %>
<%= tagbox @proposal %>
	<%= nested_comments @proposal.comments, false, 3 %>
	<%= render :partial => 'comments/form', :locals => {:parent => @proposal} unless @proposal.closed %>